apiVersion: v1
kind: Secret
metadata:
  name: housekeeper-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  DB_USER: "postgres"
  DB_PASSWORD: "postgres"  # Change in production!
