apiVersion: v1
kind: Service
metadata:
  name: housekeeper
  namespace: {{ .Release.Namespace }}
  labels:
    app: housekeeper
    component: maintenance
spec:
  type: ClusterIP
  ports:
    - port: 3200
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: housekeeper
